name: TensorFlow Google Cloud Container

on:
  push:
    branches:
      - main
    paths:
      - models/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: your_project_id
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud auth configure-docker

    - name: Build and tag Docker image
      run: |
        docker build -t gcr.io/your_project_id/your_image_name:latest .
        docker push gcr.io/your_project_id/your_image_name:latest
