name: TensorFlow Google Cloud Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - name: set GCP account
      run: |
        gcloud config set account deepaksingh26113@gmail.com
        gcloud auth login
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: nlp-p-387612
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        echo ${{ secrets.GCP_CREDENTIALS }} | base64 --decode > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud auth configure-docker

    - name: Build and tag Docker image
      run: |
        docker run -d --name serving_base tensorflow/serving
        docker cp emo-class/models/deploy serving_base:/models/deploy
        docker commit --change "ENV MODEL_NAME deploy" serving_base new_name
        docker tag new_name europe-west1-docker.pkg.dev/nlp-p-387612/emotion/new_name
        docker push europe-west1-docker.pkg.dev/nlp-p-387612/emotion/new_name
