name: TensorFlow Google Cloud Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: your_project_id
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        echo ${{ secrets.GCP_CREDENTIALS }} | base64 --decode > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud auth configure-docker

    - name: Build and tag Docker image
      run: |
        docker run -d --name serving_base tensorflow/serving
        docker cp emo-class/models/deploy serving_base:/models/deploy
        docker commit --change "ENV MODEL_NAME deploy" serving_base new_name
        docker tag new_name europe-west1-docker.pkg.dev/nlp-p-387612/emotion/new_name
        docker push europe-west1-docker.pkg.dev/nlp-p-387612/emotion/new_name
